sonar.projectKey=LucasGois1_depgraph
sonar.organization=lucasgois1
sonar.host.url=https://sonarcloud.io

sonar.sources=depviz-core/src/main/java,depviz-maven-plugin/src/main/java,depviz-cli/src/main/java,depviz-gradle-plugin/src/main/java,viewer/src
sonar.tests=depviz-core/src/test/java,depviz-maven-plugin/src/test/java,depviz-cli/src/test/java,depviz-gradle-plugin/src/test/java,viewer/src
sonar.test.inclusions=viewer/src/**/*.test.ts,viewer/src/**/*.test.tsx
sonar.exclusions=viewer/coverage/**,viewer/dist/**,viewer/node_modules/**,viewer/src/**/*.test.ts,viewer/src/**/*.test.tsx,**/target/**,**/build/**
sonar.coverage.exclusions=viewer/src/main.tsx,viewer/src/types.ts

sonar.java.binaries=depviz-core/target/classes,depviz-maven-plugin/target/classes,depviz-cli/target/classes,depviz-gradle-plugin/build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=depviz-core/target/site/jacoco/jacoco.xml,depviz-maven-plugin/target/site/jacoco/jacoco.xml,depviz-cli/target/site/jacoco/jacoco.xml,depviz-gradle-plugin/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=viewer/coverage/lcov.info
